name: Vaccine Availability Telegram Notifier CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      TELEGRAM_BOT_KEY: ${{ secrets.TELEGRAM_BOT_KEY }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      MONGO_CONN_URL: ${{ secrets.MONGO_CONN_URL }}
      DATABASE: ${{ secrets.DATABASE }}
      USER_COLLECTION: ${{ secrets.USER_COLLECTION }}
      GROUPS_COLLECTION: ${{ secrets.GROUPS_COLLECTION }}
    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test common module
      run: |
        pytest common/tests.py
    - name: Test svc module
      run: |
        pytest svc/tests.py
